### ISSUE TITLE
OpenAI API TPM limits

### ISSUE THREAD

**Issue by betinkaraman** [DrShushen/climb#13]
RateLimitError: Error code: 429 - {'error': {'message': 'Request too large for gpt-4o in organization org-VDAWofJASuLH0vVz8o9tiQZr on tokens per min (TPM): Limit 30000, Requested 30601. The input or output tokens must be reduced in order to run successfully. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

I think there should be a setting for limit params like TPM.

**Comment by DrShushen** [comment]
Thank you for this suggestion!
I have added this here: https://github.com/vanderschaarlab/climb/issues
Please submit issues on that repo going forward.
